apiVersion: apps/v1
kind: Deployment
metadata:
  name: pharma-ml-pipeline
  labels:
    app: pharma-ml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pharma-ml
  template:
    metadata:
      labels:
        app: pharma-ml
    spec:
      containers:
      - name: pharma-ml-training
        image: $ACR_NAME.azurecr.io/pharma-ml:latest
        resources:
          limits:
            nvidia.com/gpu: 1
          requests:
            nvidia.com/gpu: 1
        env:
        - name: MLFLOW_TRACKING_URI
          value: "http://mlflow-service:5000"
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
        - name: model-volume
          mountPath: /app/models
      nodeSelector:
        accelerator: nvidia-tesla
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: data-pvc
      - name: model-volume
        persistentVolumeClaim:
          claimName: model-pvc
