apiVersion: v1
kind: Node
metadata:
  name: gpu-node-template
  labels:
    accelerator: nvidia-tesla
    node-role.kubernetes.io/worker: ""
spec:
  taints:
  - key: nvidia.com/gpu
    value: "true"
    effect: NoSchedule
