apiVersion: v1
kind: Secret
metadata:
  name: azure-credentials
type: Opaque
data:
  # Base64 encoded secrets - replace with your actual credentials
  AZURE_STORAGE_CONNECTION_STRING: YmFzZTY0X2VuY29kZWRfc3RyaW5n
  KAGGLE_USERNAME: YmFzZTY0X2VuY29kZWRfdXNlcm5hbWU=
  KAGGLE_KEY: YmFzZTY0X2VuY29kZWRfa2V5
