apiVersion: v1
kind: ServiceAccount
metadata:
  name: pharma-ml-service-account
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pharma-ml-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pharma-ml-role-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: pharma-ml-service-account
  namespace: default
roleRef:
  kind: Role
  name: pharma-ml-role
  apiGroup: rbac.authorization.k8s.io
