[project]
repo_url = "https://git.axelera.ai/ai-hw-team/pipewatch/pipewatch"
docs_url = "https://doc.axelera.ai/ai-hw-team/pipewatch/pipewatch"

[package]
version = "0.3.2"
package_name = "pipewatch"
python_version = "3.10"

[package.repositories.gitlab]
url = "https://git.axelera.ai/api/v4/projects/246/packages/pypi/"
username = "gitlab-ci-token"

[package.repositories.nexus]
url = "http://10.1.5.124/repository/pypi-axe/"
username = "pypi-axe"

[package.repositories.silverlight]
url = "http://silverlight-host-0-zrh:4532/"
username = "gitlab-runner"

[release]
version_variables = [
    "pipewatch/cli.py:__version__",
]

[docs]
landing_page = "user_guide/tutorial/log_dashboard.md"
macros_modules = [
    "mkdocs_macros_lib",
    "mkdocs_macros_local",
]

[envs.docs]
extra_dependencies = [
    "mkdocs-macros-lib >= 0.1, <= 0.2",
    "mkdocs-macros-helper >= 0.1, <= 0.2",
    "-e scripts/mkdocs-macros-local",
]

[lint]
exclude_paths = [
    "tests/",
    "scripts/",
]
